import 'package:flutter/material.dart';

const Map<String, IconData> myCustomIcons = {
  'alarm clock': Icons.alarm_outlined,
  'access time': Icons.access_time_rounded,
  'car': Icons.directions_car_rounded,
  'bike': Icons.directions_bike_rounded,
  'wallet': Icons.account_balance_wallet_rounded,
  'airplane': Icons.airplanemode_active_rounded,
  'audio': Icons.audiotrack_rounded,
  'dollar': Icons.attach_money_rounded,
  'battery': Icons.battery_std_rounded,
  'beach': Icons.beach_access_rounded,
  'bookmark': Icons.bookmark_rounded,
  'brush': Icons.brush,
  'business': Icons.business_center_rounded,
  'cake': Icons.cake_rounded,
  'call': Icons.call_rounded,
  'camera': Icons.camera_alt_rounded,
  'message': Icons.chat_rounded,
  'cloud': Icons.cloud_rounded,
  'pen': Icons.create_rounded,
  'run': Icons.directions_run_rounded,
  'walk': Icons.directions_walk_rounded,
  'compass': Icons.explore_rounded,
  'heart': Icons.favorite_rounded,
  'dumbell': Icons.fitness_center_rounded,
  'flag': Icons.flag_rounded,
  'break': Icons.free_breakfast_rounded,
  'golf': Icons.golf_course_rounded,
  'star': Icons.star_rounded,
  'headphones': Icons.headphones_rounded,
  'home': Icons.home_rounded,
  'bed': Icons.hotel_rounded,
  'laptop': Icons.laptop_rounded,
  'shopping cart': Icons.local_grocery_store_rounded,
  'flower': Icons.local_florist_rounded,
  'food': Icons.local_restaurant_rounded,
  'petrol': Icons.local_gas_station_rounded,
  'email': Icons.email_rounded,
  'mic': Icons.mic_rounded,
  'pet': Icons.pets_rounded,
  'school': Icons.school_rounded,
  'shield': Icons.shield_rounded,
  'key': Icons.vpn_key_rounded,
  'toy': Icons.toys_rounded,
  'fire': Icons.whatshot_rounded,
  'sofa': Icons.weekend_rounded
};
