// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcIjFKa2czJ55ZTM93JPeXtpC2qOUjBkc',
    appId: '1:396216193677:web:80bada48433046b5f308c4',
    messagingSenderId: '396216193677',
    projectId: 'habbit-application',
    authDomain: 'habbit-application.firebaseapp.com',
    storageBucket: 'habbit-application.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKsUa_E_ay1LeJGPagB6BkBKHES_fbt_I',
    appId: '1:396216193677:android:efd29be974858b1cf308c4',
    messagingSenderId: '396216193677',
    projectId: 'habbit-application',
    storageBucket: 'habbit-application.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5f8KSrOi2RJo5JnaudayztZTNx0ymIRo',
    appId: '1:396216193677:ios:1b017fdae06d75fcf308c4',
    messagingSenderId: '396216193677',
    projectId: 'habbit-application',
    storageBucket: 'habbit-application.appspot.com',
    iosBundleId: 'com.example.habbitApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5f8KSrOi2RJo5JnaudayztZTNx0ymIRo',
    appId: '1:396216193677:ios:1b017fdae06d75fcf308c4',
    messagingSenderId: '396216193677',
    projectId: 'habbit-application',
    storageBucket: 'habbit-application.appspot.com',
    iosBundleId: 'com.example.habbitApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDcIjFKa2czJ55ZTM93JPeXtpC2qOUjBkc',
    appId: '1:396216193677:web:904fc806d3746205f308c4',
    messagingSenderId: '396216193677',
    projectId: 'habbit-application',
    authDomain: 'habbit-application.firebaseapp.com',
    storageBucket: 'habbit-application.appspot.com',
  );
}
